name: Daily CAT Countdown

on:
  schedule:
    # 03:30 UTC is 09:00 AM IST
    - cron: '30 3 * * *'
  workflow_dispatch: # Allows manual trigger execution for testing

jobs:
  send_reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests pillow

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python countdown.py
